In [1]:
# MIMO detection using Machine Learning including softmax when M=2

import tensorflow as tf
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
xy = np.loadtxt('ML_BER_2.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, :]
y_data = xy[:, -4:]

print(x_data.shape, y_data.shape)

(36000, 16) (36000, 4)


In [3]:
print(y_data)

[[ 0.70710677 -0.70710677  0.70710677  0.70710677]
 [ 0.70710677 -0.70710677  0.70710677  0.70710677]
 [ 0.70710677 -0.70710677  0.70710677  0.70710677]
 ...
 [ 0.70710677  0.70710677  0.70710677 -0.70710677]
 [ 0.70710677  0.70710677  0.70710677 -0.70710677]
 [ 0.70710677  0.70710677  0.70710677 -0.70710677]]


In [4]:
# Convert y_data to y_bit
i=1
y_merge = []
while i <= y_data.shape[0]:
    temp = "".join(str(_) for _ in y_data[i-1,:])
    y_merge.append(temp)
    i = i + 1

encoder = LabelEncoder()
encoder.fit(y_merge)
y_bit = encoder.transform(y_merge)
y_bit = y_bit.reshape(-1, 1)
print(y_bit)

[[1]
 [1]
 [1]
 ...
 [2]
 [2]
 [2]]


In [5]:
# Convert y_data to one_hot
nb_classes = 4
y_one_hot = tf.keras.utils.to_categorical(y_bit, nb_classes)
print("one_hot:", y_one_hot)

one_hot: [[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 ...
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]]


In [6]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=nb_classes, input_dim=x_data.shape[1], activation='softmax'))
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001), metrics=['accuracy'])
tf.model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 68        
Total params: 68
Trainable params: 68
Non-trainable params: 0
_________________________________________________________________


In [7]:
history = tf.model.fit(x_data, y_one_hot, epochs=100)

Epoch 1/100
1125/1125 [==============================] - 2s 1ms/step - loss: 1.6399 - accuracy: 0.2718
Epoch 2/100
1125/1125 [==============================] - 1s 1ms/step - loss: 1.3997 - accuracy: 0.3523
Epoch 3/100
1125/1125 [==============================] - 2s 1ms/step - loss: 1.2063 - accuracy: 0.4748
Epoch 4/100
1125/1125 [==============================] - 2s 2ms/step - loss: 1.0481 - accuracy: 0.6310
Epoch 5/100
1125/1125 [==============================] - 2s 2ms/step - loss: 0.9169 - accuracy: 0.7973
Epoch 6/100
1125/1125 [==============================] - 2s 2ms/step - loss: 0.8063 - accuracy: 0.9205
Epoch 7/100
1125/1125 [==============================] - 2s 2ms/step - loss: 0.7115 - accuracy: 0.9803
Epoch 8/100
1125/1125 [==============================] - 2s 2ms/step - loss: 0.6287 - accuracy: 0.9968
Epoch 9/100
1125/1125 [==============================] - 2s 1ms/step - loss: 0.5559 - accuracy: 0.9997
Epoch 10/100
1125/1125 [==============================] - 2s 1ms/step - l

1125/1125 [==============================] - 1s 1ms/step - loss: 6.7612e-05 - accuracy: 1.0000
Epoch 80/100
1125/1125 [==============================] - 2s 1ms/step - loss: 5.9420e-05 - accuracy: 1.0000
Epoch 81/100
1125/1125 [==============================] - 1s 1ms/step - loss: 5.2224e-05 - accuracy: 1.0000
Epoch 82/100
1125/1125 [==============================] - 2s 2ms/step - loss: 4.5902e-05 - accuracy: 1.0000
Epoch 83/100
1125/1125 [==============================] - 2s 2ms/step - loss: 4.0357e-05 - accuracy: 1.0000
Epoch 84/100
1125/1125 [==============================] - 2s 2ms/step - loss: 3.5491e-05 - accuracy: 1.0000
Epoch 85/100
1125/1125 [==============================] - 2s 2ms/step - loss: 3.1210e-05 - accuracy: 1.0000
Epoch 86/100
1125/1125 [==============================] - 2s 2ms/step - loss: 2.7452e-05 - accuracy: 1.0000
Epoch 87/100
1125/1125 [==============================] - 2s 2ms/step - loss: 2.4155e-05 - accuracy: 1.0000
Epoch 88/100
1125/1125 [=================

In [8]:
# Full x_data test
test_data = np.loadtxt('ML_BER_2_test.csv', delimiter=',', dtype=np.float32)
x_test_data = test_data[:, :]
y_test_data = test_data[:, -4:]
print(x_test_data.shape, y_test_data.shape)

(4000, 16) (4000, 4)


In [9]:
# Convert y_test_data to y_test_bit
i=1
y_test_merge = []
while i <= y_test_data.shape[0]:
    temp2 = "".join(str(_) for _ in y_test_data[i-1,:])
    y_test_merge.append(temp2)
    i = i + 1

encoder = LabelEncoder()
encoder.fit(y_test_merge)
y_test_bit = encoder.transform(y_test_merge)
y_test_bit = y_test_bit.reshape(-1, 1)
print(y_test_bit)

[[1]
 [1]
 [1]
 ...
 [2]
 [2]
 [2]]


In [10]:
predict_x = tf.model.predict(x_test_data) 
pred = np.argmax(predict_x,axis=1)
for p, y in zip(pred, y_test_bit.flatten()):
    print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))

[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] P

[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] P

[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] P

[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] P