In [1]:
# MIMO detection using Machine Learning including softmax when M=2

import tensorflow as tf
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
xy = np.loadtxt('ML_BER_4.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, :]
y_data = xy[:, -8:]

print(x_data.shape, y_data.shape)

(576000, 48) (576000, 8)


In [3]:
print(y_data)

[[ 0.70710677 -0.70710677 -0.70710677 ...  0.70710677  0.70710677
   0.70710677]
 [ 0.70710677 -0.70710677 -0.70710677 ...  0.70710677  0.70710677
   0.70710677]
 [ 0.70710677 -0.70710677 -0.70710677 ...  0.70710677  0.70710677
   0.70710677]
 ...
 [ 0.70710677  0.70710677  0.70710677 ... -0.70710677 -0.70710677
  -0.70710677]
 [ 0.70710677  0.70710677  0.70710677 ... -0.70710677 -0.70710677
  -0.70710677]
 [ 0.70710677  0.70710677  0.70710677 ... -0.70710677 -0.70710677
  -0.70710677]]


In [4]:
# Convert y_data to y_bit
i=1
y_merge = []
while i <= y_data.shape[0]:
    temp = "".join(str(_) for _ in y_data[i-1,:])
    y_merge.append(temp)
    i = i + 1

encoder = LabelEncoder()
encoder.fit(y_merge)
y_bit = encoder.transform(y_merge)
y_bit = y_bit.reshape(-1, 1)
print(y_bit)

[[ 7]
 [ 7]
 [ 7]
 ...
 [56]
 [56]
 [56]]


In [5]:
# Convert y_data to one_hot
nb_classes = 64
y_one_hot = tf.keras.utils.to_categorical(y_bit, nb_classes)
print("one_hot:", y_one_hot)

one_hot: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [6]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=nb_classes, input_dim=x_data.shape[1], activation='softmax'))
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001), metrics=['accuracy'])
tf.model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                3136      
Total params: 3,136
Trainable params: 3,136
Non-trainable params: 0
_________________________________________________________________


In [7]:
history = tf.model.fit(x_data, y_one_hot, epochs=100)

Epoch 1/100
18000/18000 [==============================] - 29s 2ms/step - loss: 2.7812 - accuracy: 0.5508
Epoch 2/100
18000/18000 [==============================] - 30s 2ms/step - loss: 1.1479 - accuracy: 0.9999
Epoch 3/100
18000/18000 [==============================] - 29s 2ms/step - loss: 0.5708 - accuracy: 1.0000
Epoch 4/100
18000/18000 [==============================] - 28s 2ms/step - loss: 0.3090 - accuracy: 1.0000
Epoch 5/100
18000/18000 [==============================] - 28s 2ms/step - loss: 0.1740 - accuracy: 1.0000
Epoch 6/100
18000/18000 [==============================] - 30s 2ms/step - loss: 0.1001 - accuracy: 1.0000
Epoch 7/100
18000/18000 [==============================] - 32s 2ms/step - loss: 0.0582 - accuracy: 1.0000
Epoch 8/100
18000/18000 [==============================] - 33s 2ms/step - loss: 0.0341 - accuracy: 1.0000
Epoch 9/100
18000/18000 [==============================] - 32s 2ms/step - loss: 0.0201 - accuracy: 1.0000
Epoch 10/100
18000/18000 [====================

18000/18000 [==============================] - 34s 2ms/step - loss: 2.3392e-07 - accuracy: 1.0000
Epoch 75/100
18000/18000 [==============================] - 34s 2ms/step - loss: 2.3371e-07 - accuracy: 1.0000
Epoch 76/100
18000/18000 [==============================] - 34s 2ms/step - loss: 2.3504e-07 - accuracy: 1.0000
Epoch 77/100
18000/18000 [==============================] - 34s 2ms/step - loss: 2.3475e-07 - accuracy: 1.0000
Epoch 78/100
18000/18000 [==============================] - 34s 2ms/step - loss: 2.3301e-07 - accuracy: 1.0000
Epoch 79/100
18000/18000 [==============================] - 34s 2ms/step - loss: 2.3314e-07 - accuracy: 1.0000
Epoch 80/100
18000/18000 [==============================] - 34s 2ms/step - loss: 2.3352e-07 - accuracy: 1.0000
Epoch 81/100
18000/18000 [==============================] - 34s 2ms/step - loss: 2.3298e-07 - accuracy: 1.0000
Epoch 82/100
18000/18000 [==============================] - 34s 2ms/step - loss: 2.3296e-07 - accuracy: 1.0000
Epoch 83/100
1

In [8]:
# Full x_data test
test_data = np.loadtxt('ML_BER_4_test.csv', delimiter=',', dtype=np.float32)
x_test_data = test_data[:, :]
y_test_data = test_data[:, -8:]
print(x_test_data.shape, y_test_data.shape)

(64000, 48) (64000, 8)


In [9]:
# Convert y_test_data to y_test_bit
i=1
y_test_merge = []
while i <= y_test_data.shape[0]:
    temp2 = "".join(str(_) for _ in y_test_data[i-1,:])
    y_test_merge.append(temp2)
    i = i + 1

encoder = LabelEncoder()
encoder.fit(y_test_merge)
y_test_bit = encoder.transform(y_test_merge)
y_test_bit = y_test_bit.reshape(-1, 1)
print(y_test_bit)

[[ 7]
 [ 7]
 [ 7]
 ...
 [56]
 [56]
 [56]]


In [10]:
predict_x = tf.model.predict(x_test_data) 
pred = np.argmax(predict_x,axis=1)
for p, y in zip(pred, y_test_bit.flatten()):
    print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))

[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] Prediction: 7 True Y: 7
[True] P

[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Prediction: 14 True Y: 14
[True] Pre

[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Prediction: 13 True Y: 13
[True] Pre

[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Prediction: 22 True Y: 22
[True] Pre

[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Prediction: 21 True Y: 21
[True] Pre

[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Prediction: 28 True Y: 28
[True] Pre

[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Prediction: 10 True Y: 10
[True] Pre

[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] P

[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Prediction: 27 True Y: 27
[True] Pre

[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Prediction: 16 True Y: 16
[True] Pre

[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Prediction: 38 True Y: 38
[True] Pre

[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Prediction: 37 True Y: 37
[True] Pre

[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Prediction: 55 True Y: 55
[True] Pre

[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Prediction: 62 True Y: 62
[True] Pre

[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Prediction: 60 True Y: 60
[True] Pre

[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Prediction: 43 True Y: 43
[True] Pre

[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Prediction: 41 True Y: 41
[True] Pre

[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Prediction: 50 True Y: 50
[True] Pre

[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Prediction: 48 True Y: 48
[True] Pre